version: "3"

services: 
  database:
    container_name: talk-more-db  
    image: mongo:4.2.8
    restart: always
    environment: 
      - MONGO_INITDB_DATABASE=talk-more
    volumes:
      - ./database/data:/data/db
      - ./database/scripts/init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - 27017:27017

  api:
    container_name: talk-more-api
    build: api
    image: talk-more-api
    restart: always
    environment:
      - MONGO_URL=mongodb://database:27017/talk-more
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
    ports: 
      - 8080:8080
    depends_on:
      - database

  web:
    container_name: talk-more-web
    build: web-app
    image: talk-more-web
    restart: always
    volumes:
      - ./web-app:/usr/src/app/web
      - /usr/src/app/web/node_modules
    ports: 
      - 4200:4200
    depends_on:
      - api
